apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-services
  labels:
    app: payment-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-services
  template:
    metadata:
      labels:
        app: payment-services
    spec:
      containers:
        - name: payment-services
          image: payment-services:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: payment-services
spec:
  selector:
    app: payment-services
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: LoadBalancer


