apiVersion: apps/v1
kind: Deployment
metadata:
  name: gatewayservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gatewayservice
  template:
    metadata:
      labels:
        app: gatewayservice
    spec:
      containers:
        - name: gatewayservice
          image: ob/gatewayservice:latest # replace with your Docker image name
          imagePullPolicy: Never
          ports:
            - containerPort: 8020 # replace with the port your app listens on

---
apiVersion: v1
kind: Service
metadata:
  name: productservice
spec:
  type: LoadBalancer
  ports:
    - port: 8020
      targetPort: 8020
      protocol: TCP
  selector:
    app: productservice
