apiVersion: apps/v1
kind: Deployment
metadata:
  name: userservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userservice
  template:
    metadata:
      labels:
        app: userservice
    spec:
      containers:
        - name: userservice
          image: ob/userservice:latest # replace with your Docker image name
          imagePullPolicy: Never
          ports:
            - containerPort: 8010 # replace with the port your app listens on

---
apiVersion: v1
kind: Service
metadata:
  name: userservice
spec:
  type: LoadBalancer
  ports:
    - port: 8010
      targetPort: 8010
      protocol: TCP
  selector:
    app: userservice
